[package]
name = "gami-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.2", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros", "chrono"] }
gami-sdk = { path = "../sdk" }
chrono = "0.4.41"
libloading = "0.8.7"
log = "0.4.27"
iced = "0.13.1"