[package]
name = "gami-ui-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "^0.13.1"
forest-ds="1.1.7"
html_parse =  { git = "https://github.com/TomBebb/html_parse", rev = "c6225be" }