[package]
name = "gami-iced"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["svg", "advanced"] }
iced_aw = { version = "0.11.0", default-features = false, features = ["context_menu"] }
open = "5.3.1"
gami-sdk = { path = "../sdk" }